openapi: 3.1.0
info:
  title: API сервер для проекта "Six-cities"
  description: |-
    * Список ресурсов и маршрутов сервиса "Six-cities"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers |-
    description: действия с предложениями
  - name: users |-
    description: действия с пользователями
  - name: comments |-
    description: действия с комментариями
paths:
  /user/register:
    post:
      tags:
        - user
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя
      requestBody:
        description: Информация для создания нового пользователя
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
        required: true
      responses:
        "201":
          description: Пользователь зарегестрирован. Объект пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "400":
          description: Неправильно составлен запрос или неверные данные.
        "409":
          description: Пользователь с таким email уже зарегестрирован

  /user/login:
    post:
      tags:
        - user
      summary: Авторизация пользователя
      description: Авторизирует пользователя на основе email и пароля
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginUser'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loggedUser'
          description: Пользователь авторизован
        '400':
          description: Неправильно составлен запрос или неверные данные.
        '401':
          description: Неверный пароль или email
        '404':
          description: Пользователь с такими данными не найден.
        '5XX':
          description: Ошибка сервера.
    get:
      tags:
        - user
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизированному пользователю
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
          description: Пользователь аутентифицирован
        '401':
          description: Пользователь не аутентифицирован.
        '5XX':
          description: Ошибка сервера.

  /user/{userId}/avatar:
    post:
      tags:
        - user
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение аватара должно быть в формате png или jpg
      security:
        - BearerAuth: [ ]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Аватар успешно загружен.
          content:
            application/json:
              schema:
                type: object
                properties:
                  avatar:
                    type: string
                    description: URL аватара на сервере.
        '400':
          description: Неверный запрос или данные.
        '401':
          description: Требуется аутентификация.
        '403':
          description: Недостаточно прав для редатирования
        '404':
          description: Польователь не найден.
        '5XX':
          description: Ошибка сервера.

  /user/favorites/{offerId}:
    post:
      tags:
        - user
      summary: Добавить оффер в избранное
      description: Добавляет оффер в избранное
      security:
        - BearerAuth: [ ]
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
          description: Предложение добавлено в избранное
        '400':
          description: Неверно задан запрос.
        '401':
          description: Требуется аутентификация.
        '404':
          description: Предложение не найдено.
        "409":
          description: Такое предложение уже присутствует в избранном
        '5XX':
          description: Ошибка сервера.

    delete:
      tags:
        - user
      summary: Убрать оффер из избранного
      description: Убирает оффер из избранного
      security:
        - BearerAuth: [ ]
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Предложение удалено
        '400':
          description: Неверно задан запрос
        '401':
          description: Требуется аутентификация.
        '404':
          description: Предложение не найдено или в избранном ничего нет
        '5XX':
          description: Ошибка сервера.

  /offer:
    get:
      tags:
        - offer
      summary: Загрузить предложения
      description: Загружает предложения
      responses:
        '200':
          description: Список предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offerShort'
        '5XX':
          description: Ошибка сервера.

    post:
      tags:
        - offer
      summary: Создать предлжение
      description: Создание предложения
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
      responses:
        '201':
          description: Прдложение созданно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerDetailed'

        '400':
          description: Неверно заполнены данные.
        '401':
          description: Требуется Аутентификация.
        '5XX':
          description: Ошибка сервера.

  /offer/{offerId}:
    get:
      tags:
        - offer
      summary: Загрузить предложение
      description: Загружает выбранное предлжение
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            description: Идентификатор предложения
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerDetailed'
        '400':
          description: Неверно составлен запрос.
        '404':
          description: Предложение не найдено.
        '5XX':
          description: Ошибка сервера.

    patch:
      tags:
        - offer
      summary: Обновить предлжение
      description: Вносит изменения в выбранное предложение
      security:
        - BearerAuth: [ ]
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            description: Идентификатор предложения
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offerDetailed'
        '400':
          description: Неверно составлен запрос или заполнены данные.
        '401':
          description: Требуется аутентификация
        '403':
          description: Недостаточно прав для редактирования предложения
        '404':
          description: Предложение не найдено.
        '5XX':
          description: Ошибка сервера.

    delete:
      tags:
        - offer
      summary: Удалить выбранное предложение
      description: Удаляет выбранное предложение
      security:
        - BearerAuth: [ ]
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            description: Идентификатор предложения
      responses:
        '204':
          description: Предложение успешно удалено
        '400':
          description: Неверно составлен запрос.
        '401':
          description: Требуется аутентификация.
        '404':
          description: Предложение не найдено.
        '5XX':
          description: Ошибка сервера.

  /offer/premium:
    get:
      tags:
        - offer
      summary: Загрузить премиум предложения для города
      description: Загружает премиумные предложения для города
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offerShort'
        '400':
          description: Неверно составлен запрос.
        '5XX':
          description: Ошибка сервера.



  /offer/{id}/preview:

    patch:
      tags:
        - offer
      summary: Обновить превью предлжения
      description: Загружает изображение превью предложения
      security:
        - BearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: Идентификатор предложения
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Превью оффера успешно загружено.
          content:
            application/json:
              schema:
                type: object
                properties:
                  previewImage:
                    type: string
                    description: URL превью на сервере.
        '400':
          description: Неверно составлен запрос или заполнены данные.
        '401':
          description: Требуется аутентификация
        '403':
          description: Недостаточно прав для редактирования предложения
        '404':
          description: Предложение не найдено.
        '5XX':
          description: Ошибка сервера.

  /offer/{id}/images:

    patch:
      tags:
        - offer
      summary: Обновить изображения предлжения
      description: Загружает 6 изображений для предложения
      security:
        - BearerAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: Идентификатор предложения
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: array
                    items:
                      type: string
                      description: URL изображения предложения на сервере.
        '400':
          description: Неверно составлен запрос или заполнены данные.
        '401':
          description: Требуется аутентификация
        '403':
          description: Недостаточно прав для редактирования предложения
        '404':
          description: Предложение не найдено.
        '5XX':
          description: Ошибка сервера.

  /offer/favorites:
    get:
      tags:
        - offer
      summary:  Загрузить избранные предложения
      description: Загружает избранные предложения
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offerShort'
        '400':
          description: Неверно составлен запрос.
        '401':
          description: Требуется аутентификация
        '404':
          description: Предложения не найдены.
        '5XX':
          description: Ошибка сервера.

  /comment/{offerId}:
    get:
      tags:
        - comment
      summary: Загрузить комментарии
      description: Загружает комментарии для выбранного предложения
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список комментариев
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'
        '400':
          description: Неправильно составлен запрос.
        '404':
          description: Предложение для комментария с таким id не найдено.
        '5XX':
          description: Ошибка сервера.

    post:
      tags:
        - comment
      summary: Создать комментарий
      description: Создать комментарий для выбранного предложения
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
      responses:
        '201':
          description: Комментарий создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        '400':
          description: Неверно составлен запрос или невалидные данные.
        '401':
          description: Требуется аутентификация.
        '404':
          description: Предложение для комментария с таким id не найдено.
        '5XX':
          description: Ошибка сервера.

components:
  schemas:
    createUser:
      type: object

      properties:
        name:
          required: true
          type: string
          example: John
        email:
          required: true
          type: string
          example: example@mail.com
        avatar:
          required: false
          type: string
          example: avatar.jpg
        password:
          required: true
          type: string
          example: somePass2112
        type:
          required: true
          type: string
          example: pro

    loggedUser:
      type: object

      properties:
        token:
          type: string
        email:
          type: string
        name:
          type: string
        avatar:
          type: string
        type:
          type: string


    loginUser:
      type: object

      properties:
        email:
          type: string
        password:
          type: string

    createOffer:
      type: object

      properties:
        title:
          type: string
        description:
          type: string
        date:
          type: string
        city:
          type: string
        isPremium:
          type: boolean
        rating:
          type: number
        type:
          type: string
        bedrooms:
          type: number
        maxAdults:
          type: number
        price:
          type: number
        goods:
          type: array
          items:
            type: string
        location:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: string

    createComment:
      type: object

      properties:
        content:
          type: string
        rating:
          type: number

    user:
      type: object

      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea
        name:
          type: string
          example: John
        email:
          type: string
          example: example@mail.com
        avatar:
          type: string
          example: avatar.jpg
        type:
          type: string
          example: regular

    offerDetailed:
      type: object

      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        date:
          type: string
        city:
          type: string
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
        type:
          type: string
        bedrooms:
          type: number
        maxAdults:
          type: number
        price:
          type: number
        goods:
          type: array
          items:
            type: string
        author:
          $ref: '#/components/schemas/user'
        commentsCount:
          type: number
        location:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: string

    offerShort:
      type: object

      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        date:
          type: string
        city:
          type: string
        previewImage:
          type: string
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
        type:
          type: string
        price:
          type: number
        author:
          $ref: '#/components/schemas/user'
        commentCount:
          type: number

    comment:
      type: object

      properties:
        content:
          type: string
        date:
          type: string
        rating:
          type: number
        author:
          $ref: '#/components/schemas/user'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
